In [1]:
import numpy as np

In [2]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

# 두 벡터의 내적
print(np.dot(a, b))

32


In [3]:
A = np.array([[1, 2], [3, 4]])
B = np.array([[5, 6], [7, 8]])

# 행렬의 곱
print(np.dot(A, B))

[[19 22]
 [43 50]]


In [1]:
import numpy as np

In [14]:
print(np.array(np.random.randint(-10, 10, 9).reshape(3, 3)))

[[ -3   9  -2]
 [  5  -1   9]
 [ -8   3 -10]]


In [26]:
import numpy as np

def leastsSquareSolve(A, b):

    pseudoInv = np.linalg.pinv(A)
    x = np.dot(pseudoInv, b) 
    return x

def main():

    A = np.array(np.random.randint(-10, 10, 6).reshape(3, 2))
    b = np.array(np.random.randint(-10, 10, 3).reshape(3, 1))

    
    x = leastsSquareSolve(A, b)
    print("선형 방정식의 근사해 x:", x)


if __name__ == "__main__":
    main()


선형 방정식의 근사해 x: [[-0.03666293]
 [-0.70520015]]
